### ISSUE TITLE
README.md Usage section contains wrong command to run

### ISSUE THREAD

**Issue by Saboteur777** [nicjo814/docker-plexmediaplayer#1]
The command mentioned in README.md
`docker run -d --privileged -v /tmp:/tmp -v --name=plexmediaplayer nicjo814/docker-plexmediaplayer`
results in an error: 
`docker: Error response from daemon: Invalid volume spec "--name=plexmediaplayer": Invalid volume destination path: '--name=plexmediaplayer' mount path must be absolute..
See 'docker run --help'.`

**Comment by nicjo814** [comment]
Finally updated the README with correct instructions and also improved the container itself.
